fix: await getVersionItem() call in getChildren
The getVersionItem() method was changed to async but the call site wasn't
updated to await it. This caused TypeScript error TS2559 where the
Promise<VersionItem> couldn't be added to TreeItem[].

Fixed by adding await to the method call on line 77.